name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   workflow_call:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@867052c23843559a6044c8d9e7391af6589b6a2d # IAM-2282-support-multiple-bases
    with:
      use-charmcraftcache: false
      node-size: xlarge
      tox-unit-test-targets: "build-prerequisites,unit"
      tox-integration-test-targets: "build-prerequisites,integration"
