name: On Pull Request

on:
  pull_request:
    paths-ignore:
      - "terraform/**"

jobs:
  lint:
    name: Lint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install dependencies
        run: python3 -m pip install tox

      - name: Run linters
        run: tox -e lint

  tests:
    name: Run Tests
    needs:
      - lint
    uses: ./.github/workflows/tests.yaml
