name: On Schedule
on:
  schedule:
    - cron: '0 8 * * MON'

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@15ae2e6fe85c1ed3ba8f301eecd68440b7cafdb1 # v1.8.3
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@15ae2e6fe85c1ed3ba8f301eecd68440b7cafdb1 # v1.8.3
    with:
      use-charmcraftcache: true
      node-size: xlarge
      tox-unit-test-targets: "build-prerequisites,unit"
      tox-integration-test-targets: "build-prerequisites,integration"
