name: Publish Charm

on:
  workflow_call:
    inputs:
      source_branch:
        description: source branch to publish
        default: ''
        required: false
        type: string
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

  workflow_dispatch:
    inputs:
      destination_channel:
        description: CharmHub channel to publish to
        required: false
        default: 'latest/edge'
        type: string
      source_branch:
        description: source branch to publish
        required: false
        default: ''
        type: string

jobs:
  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.source_branch }}

      - name: Select CharmHub channel
        uses: canonical/charming-actions/channel@1753e0803f70445132e92acd45c905aba6473225 # 2.7.0
        id: select-channel
        if: ${{ inputs.destination_channel == '' }}

      - name: Parse and combine inputs
        id: parse-inputs
        run: |
          # destination_channel
          destination_channel="${{ inputs.destination_channel || steps.select-channel.outputs.name }}"
          echo "setting output of destination_channel=$destination_channel"
          echo "::set-output name=destination_channel::$destination_channel"

      - name: Setup lxd
        uses: canonical/setup-lxd@v0.1.2
        with:
          channel: latest/stable

      - name: Upload charm to CharmHub
        uses: canonical/charming-actions/upload-charm@1753e0803f70445132e92acd45c905aba6473225 # 2.7.0
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          channel: ${{ steps.parse-inputs.outputs.destination_channel }}
          destructive-mode: false
