name: Run Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox -e build-prerequisites,unit

  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    needs:
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.28-strict/stable
          juju-channel: 3.4
          bootstrap-options: '--agent-version=3.4.0'

      - name: Run integration tests
        run: tox -e build-prerequisites,integration -- --model testing

      - name: Get contexts
        run: kubectl config view
        if: failure()

      - name: Get juju status
        run: juju status --relations
        if: failure()

      - name: Get juju glauth-utils logs
        run: juju debug-log --replay --include glauth-utils
        if: failure()

      - name: Get glauth juju logs
        run: juju debug-log --replay --include glauth-k8s
        if: failure()
